namespace KeyForge.Core.Keyboard;

public static class KeyboardLayout
{
    public static IReadOnlyList<KeyVisualDefinition> VisualKeys { get; } =
    [
        new("Esc", "Esc", 0, 0, 1.1),
        new("F1", "F1", 2, 0),
        new("F2", "F2", 3, 0),
        new("F3", "F3", 4, 0),
        new("F4", "F4", 5, 0),
        new("F5", "F5", 6.4, 0),
        new("F6", "F6", 7.4, 0),
        new("F7", "F7", 8.4, 0),
        new("F8", "F8", 9.4, 0),
        new("F9", "F9", 10.8, 0),
        new("F10", "F10", 11.8, 0),
        new("F11", "F11", 12.8, 0),
        new("F12", "F12", 13.8, 0),
        new("PrintScreen", "PrtSc", 15.6, 0),
        new("ScrollLock", "ScrLk", 16.6, 0),
        new("Pause", "Pause", 17.6, 0),

        new("Backquote", "`", 0, 1),
        new("D1", "1", 1, 1),
        new("D2", "2", 2, 1),
        new("D3", "3", 3, 1),
        new("D4", "4", 4, 1),
        new("D5", "5", 5, 1),
        new("D6", "6", 6, 1),
        new("D7", "7", 7, 1),
        new("D8", "8", 8, 1),
        new("D9", "9", 9, 1),
        new("D0", "0", 10, 1),
        new("Minus", "-", 11, 1),
        new("Equal", "=", 12, 1),
        new("Backspace", "Backspace", 13, 1, 2),
        new("Insert", "Ins", 15.6, 1),
        new("Home", "Home", 16.6, 1),
        new("PageUp", "PgUp", 17.6, 1),
        new("NumLock", "Num", 19.1, 1),
        new("NumpadDivide", "/", 20.1, 1),
        new("NumpadMultiply", "*", 21.1, 1),
        new("NumpadMinus", "-", 22.1, 1),

        new("Tab", "Tab", 0, 2, 1.5),
        new("Q", "Q", 1.5, 2),
        new("W", "W", 2.5, 2),
        new("E", "E", 3.5, 2),
        new("R", "R", 4.5, 2),
        new("T", "T", 5.5, 2),
        new("Y", "Y", 6.5, 2),
        new("U", "U", 7.5, 2),
        new("I", "I", 8.5, 2),
        new("O", "O", 9.5, 2),
        new("P", "P", 10.5, 2),
        new("LeftBracket", "[", 11.5, 2),
        new("RightBracket", "]", 12.5, 2),
        new("Backslash", "\\", 13.5, 2, 1.5),
        new("Delete", "Del", 15.6, 2),
        new("End", "End", 16.6, 2),
        new("PageDown", "PgDn", 17.6, 2),
        new("Numpad7", "7", 19.1, 2),
        new("Numpad8", "8", 20.1, 2),
        new("Numpad9", "9", 21.1, 2),
        new("NumpadPlus", "+", 22.1, 2, 1, 2),

        new("CapsLock", "Caps", 0, 3, 1.75),
        new("A", "A", 1.75, 3),
        new("S", "S", 2.75, 3),
        new("D", "D", 3.75, 3),
        new("F", "F", 4.75, 3),
        new("G", "G", 5.75, 3),
        new("H", "H", 6.75, 3),
        new("J", "J", 7.75, 3),
        new("K", "K", 8.75, 3),
        new("L", "L", 9.75, 3),
        new("Semicolon", ";", 10.75, 3),
        new("Quote", "'", 11.75, 3),
        new("Enter", "Enter", 12.75, 3, 2.25),
        new("Numpad4", "4", 19.1, 3),
        new("Numpad5", "5", 20.1, 3),
        new("Numpad6", "6", 21.1, 3),

        new("LeftShift", "Shift", 0, 4, 2.25),
        new("Z", "Z", 2.25, 4),
        new("X", "X", 3.25, 4),
        new("C", "C", 4.25, 4),
        new("V", "V", 5.25, 4),
        new("B", "B", 6.25, 4),
        new("N", "N", 7.25, 4),
        new("M", "M", 8.25, 4),
        new("Comma", ",", 9.25, 4),
        new("Period", ".", 10.25, 4),
        new("Slash", "/", 11.25, 4),
        new("RightShift", "Shift", 12.25, 4, 2.75),
        new("Up", "Up", 16.6, 4),
        new("Numpad1", "1", 19.1, 4),
        new("Numpad2", "2", 20.1, 4),
        new("Numpad3", "3", 21.1, 4),
        new("NumpadEnter", "Enter", 22.1, 4, 1, 2),

        new("LeftCtrl", "Ctrl", 0, 5, 1.25),
        new("LeftWin", "Win", 1.25, 5, 1.25),
        new("LeftAlt", "Alt", 2.5, 5, 1.25),
        new("Space", "Space", 3.75, 5, 6.25),
        new("RightAlt", "Alt", 10, 5, 1.25),
        new("RightWin", "Win", 11.25, 5, 1.25),
        new("Menu", "Menu", 12.5, 5, 1.25),
        new("RightCtrl", "Ctrl", 13.75, 5, 1.25),
        new("Left", "Left", 15.6, 5),
        new("Down", "Down", 16.6, 5),
        new("Right", "Right", 17.6, 5),
        new("Numpad0", "0", 19.1, 5, 2),
        new("NumpadDecimal", ".", 21.1, 5)
    ];

    public static IReadOnlyList<IReadOnlyList<KeyDefinition>> Rows { get; } =
    [
        [
            new("Esc", "Esc", 1.1),
            new("F1", "F1", 1, true),
            new("F2", "F2"),
            new("F3", "F3"),
            new("F4", "F4"),
            new("F5", "F5", 1, true),
            new("F6", "F6"),
            new("F7", "F7"),
            new("F8", "F8"),
            new("F9", "F9", 1, true),
            new("F10", "F10"),
            new("F11", "F11"),
            new("F12", "F12"),
            new("PrintScreen", "PrtSc", 1, true),
            new("ScrollLock", "ScrLk"),
            new("Pause", "Pause")
        ],
        [
            new("Backquote", "`"),
            new("D1", "1"),
            new("D2", "2"),
            new("D3", "3"),
            new("D4", "4"),
            new("D5", "5"),
            new("D6", "6"),
            new("D7", "7"),
            new("D8", "8"),
            new("D9", "9"),
            new("D0", "0"),
            new("Minus", "-"),
            new("Equal", "="),
            new("Backspace", "Backspace", 2),
            new("Insert", "Ins", 1, true),
            new("Home", "Home"),
            new("PageUp", "PgUp"),
            new("NumLock", "Num", 1, true),
            new("NumpadDivide", "/"),
            new("NumpadMultiply", "*"),
            new("NumpadMinus", "-")
        ],
        [
            new("Tab", "Tab", 1.5),
            new("Q", "Q"),
            new("W", "W"),
            new("E", "E"),
            new("R", "R"),
            new("T", "T"),
            new("Y", "Y"),
            new("U", "U"),
            new("I", "I"),
            new("O", "O"),
            new("P", "P"),
            new("LeftBracket", "["),
            new("RightBracket", "]"),
            new("Backslash", "\\", 1.5),
            new("Delete", "Del", 1, true),
            new("End", "End"),
            new("PageDown", "PgDn"),
            new("Numpad7", "7", 1, true),
            new("Numpad8", "8"),
            new("Numpad9", "9"),
            new("NumpadPlus", "+")
        ],
        [
            new("CapsLock", "Caps", 1.8),
            new("A", "A"),
            new("S", "S"),
            new("D", "D"),
            new("F", "F"),
            new("G", "G"),
            new("H", "H"),
            new("J", "J"),
            new("K", "K"),
            new("L", "L"),
            new("Semicolon", ";"),
            new("Quote", "'"),
            new("Enter", "Enter", 2.2),
            new("Numpad4", "4", 1, true),
            new("Numpad5", "5"),
            new("Numpad6", "6")
        ],
        [
            new("LeftShift", "Shift", 2.3),
            new("Z", "Z"),
            new("X", "X"),
            new("C", "C"),
            new("V", "V"),
            new("B", "B"),
            new("N", "N"),
            new("M", "M"),
            new("Comma", ","),
            new("Period", "."),
            new("Slash", "/"),
            new("RightShift", "Shift", 2.7),
            new("Up", "Up", 1, true),
            new("Numpad1", "1", 1, true),
            new("Numpad2", "2"),
            new("Numpad3", "3"),
            new("NumpadEnter", "Enter")
        ],
        [
            new("LeftCtrl", "Ctrl", 1.4),
            new("LeftWin", "Win", 1.2),
            new("LeftAlt", "Alt", 1.2),
            new("Space", "Space", 6.2),
            new("RightAlt", "Alt", 1.2),
            new("RightWin", "Win", 1.2),
            new("Menu", "Menu", 1.2),
            new("RightCtrl", "Ctrl", 1.4),
            new("Left", "Left", 1, true),
            new("Down", "Down"),
            new("Right", "Right"),
            new("Numpad0", "0", 2, true),
            new("NumpadDecimal", ".")
        ]
    ];
}
